dist: bionic
language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - travis_retry composer update --no-progress --prefer-dist

script:
  - vendor/bin/phpunit -c phpunit.xml --testdox --verbose

matrix:
  fast_finish: true

branches:
  only:
    - main